# 지킬에 오신 것을 환영합니다!
#
# 이 구성 파일은 전체 사이트, 값에 영향을 미치는 설정을위한 것입니다.
# 한 번 설정해야하며 그 후에는 거의 편집 할 필요가 없습니다.
# 처음 인 것들이 파일은 사용할 때 자동으로 다시로드되지 않습니다 *
# `jekyll serve`. 이 파일을 변경하는 경우 서버 프로세스를 다시 시작하십시오.

# 테마 설정
#
# 문서를 검토하여`theme` 또는`remote_theme`를 있는지 결정합니다.
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# 테마 : "최소한의 실수 제킬"
# remote_theme : "mmistakes / 최소한의 실수"
minimal_mistakes_skin     : " default "  # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 사이트 설정
로케일                    : " en-US "
제목                     : " 사이트 제목 "
title_separator           : " - "
subtitle                  : # 마스트 헤드의 사이트 제목 아래에 표시되는 사이트 태그 라인
이름                      : " 당신의 이름 "
설명               : " 놀라운 웹 사이트입니다. "
url                       : # 사이트의 기본 호스트 이름 및 프로토콜 (예 : "https://mmistakes.github.io")
baseurl                   : # 사이트의 하위 경로, 예 : "/ blog"
repository                : # GitHub 사용자 이름 / repo-name 예 : "mmistakes / minimal-mistakes"
teaser : # 대체 티저                    이미지 경로, 예 : "/assets/images/500x300.png"
logo                      : # 마스트 헤드에 표시 할 로고 이미지의 경로 (예 : "/assets/images/88x88.png")
masthead_title : # 마스트 헤드에             웹 사이트 제목을 재정의합니다. 제목이 ""를 사용합니다.
# breadcrumbs : false # true, false
분당 단어 수          : 200
댓글 :
  provider                : # false (병원), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus :
    짧은 이름             : # https://help.disqus.com/customer/portal/articles/466208-what-sa-shortname-
  담화 :
    서버                : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963, 예 : meta.discourse.org
  페이스 북 :
    # https://developers.facebook.com/docs/plugins/comments
    appid                 :
    num_posts             : # 5
    colorscheme           : # "빛"(공용), "어두움"
  발화 :
    테마                 : # "github-light"(이전), "github-dark"
    issue_term            : # "경로 이름"
  staticman :
    branch                : # "마스터"
    endpoint              : # "https : // {your Staticman v3 API} / v3 / entry / github /"
reCaptcha :
  siteKey                 :
  비밀                  :
atom_feed :
  path                    : # 공백 (공용)은 feed.xml을 사용합니다.
  hide                    : # 참, 거짓
검색                    : # 참, 거짓 (특허)
search_full_content       : # 참, 거짓
search_provider           : # lunr (당뇨), algolia, google
algolia :
  application_id          : # YOUR_APPLICATION_ID
  index_name              : # YOUR_INDEX_NAME
  search_only_api_key     : # YOUR_SEARCH_ONLY_API_KEY
  power_by              : # 참 (공용), 거짓
구글 :
  search_engine_id        : # YOUR_SEARCH_ENGINE_ID
  instant_search          : # 거짓 (공용), 참
# SEO 관련
google_site_verification :
bing_site_verification    :
yandex_site_verification :
naver_site_verification   :

# 소셜 공유
트위터 :
  사용자 이름                :
페이스 북 :
  사용자 이름                :
  app_id                  :
  출판사               :
og_image                  : # 오픈 그래프 / 트위터 기본 사이트 이미지
# 소셜 프로필 지정
# -https : //developers.google.com/structured-data/customize/social-profiles
사회 :
  유형                    : # 사람 또는 조직 (개원은 사람)
  name                    : # 사용자 또는 조직 이름이 사이트 이름과 다른 경우
  links : # 소셜 미디어 프로필에 대한 홍보의 링크

# 분석
분석 :
  provider                : false # false (당뇨), "google", "google-universal", "google-gtag", "custom"
  구글 :
    tracking_id           :
    anonymize_ip          : # 참, 거짓


# 사이트 작성자
저자 :
  이름              : " 당신의 이름 "
  avatar            : # 아바타 이미지 경로, 예 : "/assets/images/bio-photo.jpg"
  약력               : " 나는 ** 놀라운 ** 사람이다. "
  위치          : " 어딘가 "
  이메일             :
  링크 :
    - 라벨 : " 이메일 "
      아이콘 : " fas fa-fw fa-envelope-square "
      # URL : "mailto : your.name@email.com"
    - 레이블 : " 웹 사이트 "
      아이콘 : " fas fa-fw fa-link "
      # URL : "https://your-website.com"
    - 라벨 : " Twitter "
      아이콘 : " fab fa-fw fa-twitter-square "
      # URL : "https://twitter.com/"
    - 레이블 : " Facebook "
      아이콘 : " fab fa-fw fa-facebook-square "
      # URL : "https://facebook.com/"
    - 라벨 : " GitHub "
      아이콘 : " fab fa-fw fa-github "
      # URL : "https://github.com/"
    - 라벨 : " Instagram "
      아이콘 : " fab fa-fw fa-instagram "
      # URL : "https://instagram.com/"

# 사이트 바닥 글
바닥 글 :
  링크 :
    - 라벨 : " Twitter "
      아이콘 : " fab fa-fw fa-twitter-square "
      # URL :
    - 레이블 : " Facebook "
      아이콘 : " fab fa-fw fa-facebook-square "
      # URL :
    - 라벨 : " GitHub "
      아이콘 : " fab fa-fw fa-github "
      # URL :
    - 라벨 : " GitLab "
      아이콘 : " fab fa-fw fa-gitlab "
      # URL :
    - 라벨 : " Bitbucket "
      아이콘 : " fab fa-fw fa-bitbucket "
      # URL :
    - 라벨 : " Instagram "
      아이콘 : " fab fa-fw fa-instagram "
      # URL :


# 파일 읽기
포함 :
  - htaccess로로
  - _pages
제외 :
  - " * .sublime-project "
  - " * .sublime-workspace "
  - 공급 업체
  - .asset 캐시
  - .bundle
  - .jekyll - 자산 캐시
  - .sass 캐시
  - 자산 / js / 플러그인
  - 자산 / JS / _main.js
  - 자산 / js / 공급 업체
  - 캡 파일
  -변경 로그
  - 구성
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - 라이센스
  - 로그
  - 노드 모듈
  - package.json
  - 패키지 lock.json
  - 레이크 파일
  - 읽어보기
  - TMP
  - / docs # 최소한의 실수 무시 / docs
  - / test # 최소한의 실수 무시 / test
keep_files :
  - .git
  - 을 .svn
인코딩 : " utf-8 "
markdown_ext : " markdown, mkdown, mkdn, mkd, md "


# 변환
마크 다운 : kramdown
형광펜 : 루즈
lsi : 거짓
excerpt_separator : " \ n \ n "
증분 : 거짓


# 마크 다운 처리
크램 다운 :
  입력 : GFM
  hard_wrap : false
  auto_ids : true
  footnote_nr : 1
  entity_output : as_char
  toc_levels : 1..6
  smart_quotes : lsquo, rsquo, ldquo, rdquo
  enable_coderay : false


# Sass / SCSS
sass :
  sass_dir : _sass
  스타일 : 압축 # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# 출력
퍼머 링크 : / : 카테고리 / : 제목 /
paginate : 5  # 표시 할 게시물 수
paginate_path : / 페이지 : 번호 /
존재 : # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# 플러그인 (이전에는 gems :)
플러그인 :
  - 지킬 페이지
  - 지킬-사이트 맵
  - 지킬 요지
  - 지킬 피드
  - 지킬 -포함 캐시를

# --safe로 GitHub 페이지 모방
허용 목록 :
  - 지킬 페이지
  - 지킬-사이트 맵
  - 지킬 요지
  - 지킬 피드
  - 지킬 -포함 캐시를


# 아카이브
#    유형
#    -Liquid로 빌드 된 GitHub Pages 호환 아카이브 페이지 ~> 종류 : 액체
#    -Jekyll Archives 플러그인 아카이브 페이지 ~> 유형 : jekyll-archives
#    경로 (예제)
#    -액체 방법을 사용할 때 경로에 아카이브 페이지가 있어야합니다.
#      더러워진 링크 예상
#    -<base_path> /tags/my-awesome-tag/index.html ~> 경로 : / tags /
#    -<base_path> /categories/my-awesome-category/index.html ~> 경로 : / categories /
#    -<base_path> /my-awesome-category/index.html ~> 경로 : /
category_archive :
  유형 : 액체
  경로 : / 카테고리 /
tag_archive :
  유형 : 액체
  경로 : / 태그 /
# https://github.com/jekyll/jekyll-archives
# jekyll-archives :
#     활성화 됨 :
#       -문구
#       -태그
#     레이아웃 :
#       카테고리 : 아카이브 분류
#       태그 : 아카이브 분류
   영구 링크 # 개 :
#       카테고리 : / 카테고리 / : 이름 /
#       태그 : / tags / : 이름 /


# HTML 압축
# -https : //jch.penibelst.de/
compress_html :
  스크랩 : 모두
  무시 :
    envs : 개발


# 부케
부케 :
  # _posts
  - 범위 :
      경로 : " "
      유형 : 게시물
    값 :
      레이아웃 : 단일
      author_profile : true
      read_time : true
      댓글 : # 참
      공유 : 사실
      관련 : 사실
